cli:
	wget https://github.com/n0-computer/iroh/releases/download/v0.15.0/iroh-v0.15.0-x86_64-unknown-linux-musl.tar.gz -O iroh.tar.gz
	tar -xvf iroh.tar.gz
	rm iroh.tar.gz
	chmod +x iroh

python:
	uv pip install iroh
