name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/davidgasquez/sandbox:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run:
    name: Run
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/davidgasquez/sandbox:latest
    steps:
        - name: Run
          run: echo "Hello world"
